import http from 'node:http';
import { URL } from 'node:url';

let activeConfig = null;
const knowledge = { redis_cache: { id: 'kb.redis.cache-failure.v1', title: 'Redis 缓存异常处理', summary: '缓存击穿、缓存雪崩、缓存穿透、降级与回源控制。', source: '本地知识库条目；上线前应补充官方文档链接与版本。' } };
const json = (res, code, body) => { res.writeHead(code, { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': '*' }); res.end(JSON.stringify(body)); };
const read = req => new Promise((resolve, reject) => { let data=''; req.on('data', c => { data += c; if (data.length > 1_000_000) req.destroy(); }); req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch (e) { reject(new Error('请求 JSON 无法解析')); } }); req.on('error', reject); });
const extract = (text, terms) => terms.filter(t => text.toLowerCase().includes(t.toLowerCase()));
function ruleAnalyze({ jd='', resume='', answer='' }={}) { const source=answer.trim(), spans=[]; const add=(id,terms,label)=>{ const term=terms.find(t=>source.toLowerCase().includes(t.toLowerCase())); if(term){const at=source.toLowerCase().indexOf(term.toLowerCase()); spans.push({id,label,quote:source.slice(Math.max(0,at-16),Math.min(source.length,at+term.length+42))});} }; add('answer.solution',['redis','缓存','回填','数据库'],'技术方案'); add('answer.contribution',['我负责','我独立','我设计','我实现','主导'],'个人贡献'); add('answer.result',['%','毫秒','qps','提升','降低','减少'],'量化结果'); add('answer.fallback',['降级','回源','熔断','兜底','击穿','雪崩','穿透'],'故障兜底'); const missing=['技术方案','个人贡献','量化结果','故障兜底'].filter(x=>!spans.some(s=>s.label===x)); const req=extract(jd||'Redis 缓存 高并发 故障降级',['Redis','缓存','高并发','降级']).join('、')||'Redis 缓存异常处理'; return {mode:'rules',score:Math.round(spans.length/4*100),evidence:spans,missing,requirement:req,knowledge:knowledge.redis_cache,followUp:missing[0]?`请补充${missing[0]}：在这个场景中，你具体做了什么？`:'请说明方案的边界条件和验证方式。',consistency:resume.includes('负责系统优化')&&!spans.some(s=>s.label==='个人贡献')?[{type:'待澄清',resume:'负责系统优化',answer:source.slice(0,100)}]:[]}; }
function validOnline(result, answer) { if(!result || !Array.isArray(result.evidence)) throw new Error('模型返回缺少 evidence 数组'); const evidence=result.evidence.filter(e=>e && typeof e.quote==='string' && answer.includes(e.quote) && typeof e.label==='string'); return {...ruleAnalyze({answer}), ...result, mode:'online', evidence, score:undefined}; }
async function onlineAnalyze(input) { if(!activeConfig?.apiKey) return null; const base=activeConfig.baseUrl.replace(/\/$/,''); const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),10000); try { const r=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${activeConfig.apiKey}`},signal:controller.signal,body:JSON.stringify({model:activeConfig.model,temperature:0.1,max_tokens:900,messages:[{role:'system',content:'你是面试证据提取器。只输出 JSON：{evidence:[{label,quote,id}],missing:[string],followUp:string,requirement:string}。quote 必须逐字来自回答，不要输出分数。'}, {role:'user',content:JSON.stringify({jd:input.jd,resume:input.resume,question:input.question,answer:input.answer})}]})}); if(!r.ok) throw new Error(`模型服务 HTTP ${r.status}`); const body=await r.json(); const text=body.choices?.[0]?.message?.content; const parsed=JSON.parse(text.replace(/^```json\s*|\s*```$/g,'')); return validOnline(parsed,input.answer); } finally { clearTimeout(timer); } }
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost'); if(req.method==='OPTIONS')return json(res,204,{}); try { if(req.method==='POST'&&url.pathname==='/api/analyze'){const input=await read(req); try { const online=await onlineAnalyze(input); if(online)return json(res,200,online); } catch(e) { const fallback=ruleAnalyze(input); return json(res,200,{...fallback,mode:'rules',fallbackReason:e.name==='AbortError'?'模型超时':e.message}); } return json(res,200,ruleAnalyze(input)); } if(req.method==='POST'&&url.pathname==='/api/models'){const b=await read(req); if(!b.baseUrl||!b.model)return json(res,400,{ok:false,error:'Base URL 和模型名称不能为空'}); activeConfig={baseUrl:b.baseUrl,model:b.model,apiKey:b.apiKey||''}; return json(res,200,{ok:true,provider:b.provider,model:b.model,stored:'memory-only'});} if(req.method==='POST'&&url.pathname==='/api/models/test'){const b=await read(req); if(!b.baseUrl||!b.model)return json(res,400,{ok:false,error:'Base URL 和模型名称不能为空'}); return json(res,200,{ok:true,message:'配置格式有效；保存后将尝试在线分析，失败自动降级规则模式。'});} if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,mode:activeConfig?.apiKey?'online-configured':'offline-ready'}); return json(res,404,{error:'Not found'});} catch(e){return json(res,400,{error:e.message});}});
server.listen(process.env.PORT||8787,'127.0.0.1',()=>console.log('Evidence API listening on http://127.0.0.1:8787'));
