import http from 'node:http';
import crypto from 'node:crypto';
import { URL } from 'node:url';
import { analyzeRules, validateInput } from '../shared/analyze.mjs';

const sessions = new Map();
const json=(res,status,body,headers={})=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(body));};
const readBody=req=>new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>800000)req.destroy();});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{});}catch{reject(new Error('请求 JSON 无法解析'));}});req.on('error',reject);});
function session(req,res){let sid=(req.headers.cookie||'').match(/evidence_sid=([\w-]+)/)?.[1];if(!sid||!sessions.has(sid)){sid=crypto.randomUUID();sessions.set(sid,{config:null,cache:new Map(),createdAt:Date.now()});res.setHeader('set-cookie',`evidence_sid=${sid}; Path=/; HttpOnly; SameSite=Strict`);}return sessions.get(sid);}
function safeOrigin(req){const o=req.headers.origin;return !o||/^https?:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/.test(o);}
function parseModel(raw){const cleaned=raw.replace(/^```(?:json)?\s*|\s*```$/gi,'').trim();const out=JSON.parse(cleaned);if(!out||!Array.isArray(out.evidence)||!Array.isArray(out.missing))throw new Error('模型输出不符合证据协议');return out;}
async function online(input, config){if(!config?.apiKey)return null;const base=config.baseUrl.replace(/\/$/,'');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(`${base}/chat/completions`,{method:'POST',redirect:'error',headers:{'content-type':'application/json',authorization:`Bearer ${config.apiKey}`},signal:controller.signal,body:JSON.stringify({model:config.model,temperature:.1,max_tokens:900,messages:[{role:'system',content:'你是证据抽取器。只输出 JSON：{evidence:[{dimension,quote}],missing:[string],followUp:string}。quote 必须逐字来自回答；不要计算总分，不要声称造假。'},{role:'user',content:JSON.stringify(input)}]})});if(!r.ok)throw new Error(`模型服务 HTTP ${r.status}`);const body=await r.json();const raw=body.choices?.[0]?.message?.content;return parseModel(raw);}finally{clearTimeout(timer);}}
function mergeOnline(input, model){const base=analyzeRules(input);const exact=(model.evidence||[]).filter(e=>e&&typeof e.quote==='string'&&input.answer.includes(e.quote)&&typeof e.dimension==='string');if(!exact.length)return {...base,fallbackReason:'模型未返回可回溯回答片段'};const modelByDim=new Map(exact.map(e=>[e.dimension,e]));const evidence=base.evidence.map(e=>modelByDim.get(e.dimension)?{...e,modelHint:modelByDim.get(e.dimension)}:e);return {...base,mode:'online',evidence,modelMissing:model.missing,modelFollowUp:model.followUp||null};}
const server=http.createServer(async(req,res)=>{if(!safeOrigin(req))return json(res,403,{error:'不接受该来源'});if(req.method==='OPTIONS')return json(res,204,{});try{const s=session(req,res),url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,mode:s.config?.apiKey?'online-configured':'offline-ready'});if(req.method==='POST'&&url.pathname==='/api/analyze'){const input=validateInput(await readBody(req));const key=crypto.createHash('sha256').update(JSON.stringify({input,model:s.config?.model||'rules'})).digest('hex');if(s.cache.has(key))return json(res,200,{...s.cache.get(key),cached:true});let result;try{const model=await online(input,s.config);result=model?mergeOnline(input,model):analyzeRules(input);}catch(e){result={...analyzeRules(input),fallbackReason:e.name==='AbortError'?'模型超时':e.message};}s.cache.set(key,result);return json(res,200,result);}if(req.method==='POST'&&url.pathname==='/api/models'){const b=await readBody(req);if(!b.baseUrl||!b.model)return json(res,400,{ok:false,error:'Base URL 和模型名称不能为空'});try{const u=new URL(b.baseUrl);if(!['http:','https:'].includes(u.protocol))throw new Error('Base URL 必须使用 HTTP(S)');if(u.hostname!=='localhost'&&u.hostname!=='127.0.0.1'&&u.protocol!=='https:')throw new Error('远程模型必须使用 HTTPS');}catch(e){return json(res,400,{ok:false,error:e.message});}s.config={provider:b.provider,baseUrl:b.baseUrl,model:b.model,apiKey:b.apiKey||''};return json(res,200,{ok:true,provider:b.provider,model:b.model,stored:'memory-only'});}if(req.method==='POST'&&url.pathname==='/api/models/test'){const b=await readBody(req);return json(res,200,{ok:Boolean(b.baseUrl&&b.model),message:'配置格式检查完成'});}return json(res,404,{error:'Not found'});}catch(e){return json(res,400,{error:e.message});}});
server.listen(process.env.PORT||8787,'127.0.0.1',()=>console.log('Evidence API listening on http://127.0.0.1:8787'));
